Attempt to support arbitrary pointers with %p with PrintfFormatter only
This code attempts to support passing arbitrary pointers to fmt::printf and
fmt::sprintf only, without enabling such support for fmt::format. It does
this by enabling the MakeValue constructor overloads appropriately
depending on the allow_arbitrary_pointer_args and
disallow_arbitrary_pointer_args types, which are specialized for
PrintfFormatter.

Unfortunately this does not work. fmt::sprintf still ends up wanting to
create MakeValue<BasicFormatter<char>> with the arbitrary pointer:

In file included from /home/mac/git/fmt/fmt/ostream.h:13:0,
                 from /home/mac/git/fmt/fmt/printf.h:16,
                 from /home/mac/git/fmt/test/printf-test.cc:32:
/home/mac/git/fmt/fmt/format.h: In instantiation of ‘static fmt::internal::Value fmt::internal::ArgArray<N, true>::make(const T&) [with Formatter = fmt::BasicFormatter<char>; T = int*; long unsigned int N = 1ul]’:
/home/mac/git/fmt/fmt/printf.h:558:1:   required from ‘std::__cxx11::string fmt::sprintf(fmt::CStringRef, const Args& ...) [with Args = {int*}; std::__cxx11::string = std::__cxx11::basic_string<char>; fmt::CStringRef = fmt::BasicCStringRef<char>]’
b/home/mac/git/fmt/test/printf-test.cc:464:34:   required from here
/home/mac/git/fmt/fmt/format.h:2468:12: error: ‘fmt::internal::MakeValue<Formatter>::MakeValue(T*, typename fmt::internal::disallow_arbitrary_pointer_args<Formatter, T>::type) [with T = int; Formatter = fmt::BasicFormatter<char>; typename fmt::internal::disallow_arbitrary_pointer_args<Formatter, T>::type = int]’ is private within this context
     return MakeValue<Formatter>(value);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~